locomotion_param:
  b_optimize_timings: true
  bound_phase_duration:
  - 0.15
  - 0.15
  costs:
    w_BaseAngVelDiffCost:
    - 0.1
    - 0.1
    - 0.1
    w_BaseLinVelDiffCost:
    - 0.1
    - 0.1
    - 1.0
    w_FinalBaseAngPosCost:
    - 2.0
    - 2.0
    - 2.0
    w_FinalBaseAngVelCost:
    - 1.0
    - 1.0
    - 1.0
    w_FinalBaseLinPosCost:
    - 2.0
    - 2.0
    - 2.0
    w_FinalBaseLinVelCost:
    - 1.0
    - 1.0
    - 1.0
    w_FinalEEMotionAngPosCost:
    - 2.0
    - 2.0
    - 2.0
    w_FinalEEMotionLinPosCost:
    - 2.0
    - 2.0
    - 20.0
    w_IntermediateBaseAngVelCost:
    - 0.01
    - 0.01
    - 0.01
    w_IntermediateBaseLinPosCost:
    - 0
    - 0.1
    - 100.0
    w_IntermediateBaseLinVelCost:
    - 0.001
    - 0.001
    - 1.0
    w_WrenchAngPosCost:
    - 0.1
    - 0.1
    - 0.01
    w_WrenchAngVelCost:
    - 0.01
    - 0.01
    - 0.01
    w_WrenchAngVelDiffCost:
    - 0.001
    - 0.001
    - 0.001
    w_WrenchLinPosCost:
    - 0.1
    - 0.1
    - 0.01
    w_WrenchLinVelCost:
    - 0.01
    - 0.01
    - 0.01
    w_WrenchLinVelDiffCost:
    - 0.001
    - 0.001
    - 0.001
  dt_constraint_base_motion: 0.025
  dt_constraint_dynamic: 0.1
  dt_constraint_range_of_motion: 0.08
  duration_base_polynomial: 0.1
  ee_in_contact_at_start:
    0: true
    1: true
  ee_phase_durations:
    0:
    - 0.5
    - 0.75
    - 1.65
    - 0.75
    - 1.65
    1:
    - 2.0
    - 0.75
    - 1.65
    - 0.75
    - 0.15
  ee_polynomials_per_swing_phase: 2
  force_limit_in_normal_direction: 1000.0
  force_polynomials_per_stance_phase: 3
locomotion_task:
  final_base_ang:
  - 0.0
  - 0.0
  - 0.844153986113171
  - 0.0
  - 0.0
  - 0.0
  final_base_lin:
  - 3.9000000000000004
  - 2.8000000000000003
  - 1.0314705882352941
  - 0.0
  - 0.0
  - 0.0
  initial_base_ang:
  - 0.0
  - 0.0
  - 0.8441539861131709
  - 0.0
  - 0.0
  - 0.0
  initial_base_lin:
  - 3.1
  - 1.9000000000000001
  - 1.0241176470588236
  - 0.0
  - 0.0
  - 0.0
  initial_ee_motion_ang:
    0:
    - 0.0
    - 0.0
    - 0.8441539861131709
    1:
    - 0.0
    - 0.0
    - 0.8441539861131709
  initial_ee_motion_lin:
    0:
    - 2.997604923340339
    - 1.9910178459196992
    - 0.04411764705882353
    1:
    - 3.2023950766596614
    - 1.808982154080301
    - 0.04411764705882353
  terrain_type: terrain
solver: ipopt
