locomotion_param:
  b_optimize_timings: true
  bound_phase_duration:
  - 0.15
  - 0.15
  costs:
    w_BaseAngVelDiffCost:
    - 0.1
    - 0.1
    - 0.1
    w_BaseLinVelDiffCost:
    - 0.1
    - 0.1
    - 1.0
    w_FinalBaseAngPosCost:
    - 2.0
    - 2.0
    - 2.0
    w_FinalBaseAngVelCost:
    - 1.0
    - 1.0
    - 1.0
    w_FinalBaseLinPosCost:
    - 2.0
    - 2.0
    - 2.0
    w_FinalBaseLinVelCost:
    - 1.0
    - 1.0
    - 1.0
    w_FinalEEMotionAngPosCost:
    - 2.0
    - 2.0
    - 2.0
    w_FinalEEMotionLinPosCost:
    - 2.0
    - 2.0
    - 20.0
    w_IntermediateBaseAngVelCost:
    - 0.01
    - 0.01
    - 0.01
    w_IntermediateBaseLinPosCost:
    - 0
    - 0.1
    - 100.0
    w_IntermediateBaseLinVelCost:
    - 0.001
    - 0.001
    - 1.0
    w_WrenchAngPosCost:
    - 0.1
    - 0.1
    - 0.01
    w_WrenchAngVelCost:
    - 0.01
    - 0.01
    - 0.01
    w_WrenchAngVelDiffCost:
    - 0.001
    - 0.001
    - 0.001
    w_WrenchLinPosCost:
    - 0.1
    - 0.1
    - 0.01
    w_WrenchLinVelCost:
    - 0.01
    - 0.01
    - 0.01
    w_WrenchLinVelDiffCost:
    - 0.001
    - 0.001
    - 0.001
  dt_constraint_base_motion: 0.025
  dt_constraint_dynamic: 0.1
  dt_constraint_range_of_motion: 0.08
  duration_base_polynomial: 0.1
  ee_in_contact_at_start:
    0: true
    1: true
  ee_phase_durations:
    0:
    - 0.5
    - 0.75
    - 1.65
    - 0.75
    - 1.65
    - 0.75
    - 0.75
    1:
    - 2.0
    - 0.75
    - 1.65
    - 0.75
    - 1.65
  ee_polynomials_per_swing_phase: 2
  force_limit_in_normal_direction: 1000.0
  force_polynomials_per_stance_phase: 3
locomotion_task:
  final_base_ang:
  - 0.0
  - 0.0
  - 0.7853981633974487
  - 0.0
  - 0.0
  - 0.0
  final_base_lin:
  - 6.300000000000001
  - 4.3
  - 1.068235294117647
  - 0.0
  - 0.0
  - 0.0
  initial_base_ang:
  - 0.0
  - 0.0
  - 0.3587706702705719
  - 0.0
  - 0.0
  - 0.0
  initial_base_lin:
  - 4.7
  - 3.7
  - 1.0388235294117647
  - 0.0
  - 0.0
  - 0.0
  initial_ee_motion_ang:
    0:
    - 0.0
    - 0.0
    - 0.3587706702705719
    1:
    - 0.0
    - 0.0
    - 0.3587706702705719
  initial_ee_motion_lin:
    0:
    - 4.65189608850239
    - 3.8282770973269593
    - 0.058823529411764705
    1:
    - 4.74810391149761
    - 3.571722902673041
    - 0.058823529411764705
  terrain_type: terrain
solver: ipopt
